/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace scripts {
  /**
  Cluster fetched data
  */
  export async function clusterwinedata(df_wine: DG.DataFrame , n_pca: number , n_clusters: number ): Promise<DG.DataFrame> {
    return await grok.functions.call('winequalitywf:Clusterwinedata', { df_wine, n_pca, n_clusters });
  }

  /**
  Fetch Wine quality dataset from web
  */
  export async function fetchwinedata(url_red: string , url_white: string ): Promise<{df_wine: DG.DataFrame, total_lines: number}> {
    return await grok.functions.call('winequalitywf:Fetchwinedata', { url_red, url_white });
  }

  /**
  Merge linear regression and clustering data
  */
  export async function mergepredictions(df_clustering: DG.DataFrame , df_regression: DG.DataFrame ): Promise<DG.DataFrame> {
    return await grok.functions.call('winequalitywf:Mergepredictions', { df_clustering, df_regression });
  }

  /**
  Train regression on wine quality data
  */
  export async function trainregression(df_wine: DG.DataFrame , test_size: number ): Promise<DG.DataFrame> {
    return await grok.functions.call('winequalitywf:Trainregression', { df_wine, test_size });
  }
}

export namespace funcs {
  export async function wineQualityWf(params: any ): Promise<any> {
    return await grok.functions.call('winequalitywf:WineQualityWf', { params });
  }
}
