/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('paramreference:Info', {});
  }

  export async function bioreactorConfiguration(): Promise<any> {
    return await grok.functions.call('paramreference:BioreactorConfiguration', {});
  }

  /**
  Get all available synthon spaces from Chem package files
  */
  export async function listBioreactors(): Promise<any> {
    return await grok.functions.call('paramreference:ListBioreactors', {});
  }
}
