/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('paramreference:Info', {});
  }

  /**
  Choose available bioreactor models and parameters - example of parameter referencing
  */
  export async function bioreactorConfiguration(bioreactor: string , impeller: string ): Promise<any> {
    return await grok.functions.call('paramreference:BioreactorConfiguration', { bioreactor, impeller });
  }

  export async function listBioreactors(): Promise<any> {
    return await grok.functions.call('paramreference:ListBioreactors', {});
  }

  export async function listImpellers(): Promise<any> {
    return await grok.functions.call('paramreference:ListImpellers', {});
  }
}
